const FETCH_REQUEST = 'notes/FETCH_REQUEST';
const FETCH_SUCCESS = 'notes/FETCH_SUCCESS';
const FETCH_ERROR = 'notes/FETCH_ERROR';

const ADD_REQUEST = 'note/ADD_REQUEST';
const ADD_SUCCESS = 'note/ADD_SUCCESS';
const ADD_ERROR = 'note/ADD_ERROR';

const UPDATE_REQUEST = 'note/UPDATE_REQUEST';
const UPDATE_SUCCESS = 'note/UPDATE_SUCCESS';
const UPDATE_ERROR = 'note/UPDATE_ERROR';

const DELETE_REQUEST = 'note/DELETE_REQUEST';
const DELETE_SUCCESS = 'note/DELETE_SUCCESS';
const DELETE_ERROR = 'note/DELETE_ERROR';

export default {
  FETCH_REQUEST,
  FETCH_SUCCESS,
  FETCH_ERROR,
  ADD_REQUEST,
  ADD_SUCCESS,
  ADD_ERROR,
  UPDATE_REQUEST,
  UPDATE_SUCCESS,
  UPDATE_ERROR,
  DELETE_REQUEST,
  DELETE_SUCCESS,
  DELETE_ERROR,
};
