const OPEN_SNACKBAR = 'snackbar/OPEN_SNACKBAR';
const CLOSE_SNACKBAR = 'snackbar/CLOSE_SNACKBAR';

const ERROR_SNACKBAR = 'snackbar/ERROR_SNACKBAR';
const INFO_SNACKBAR = 'snackbar/INFO_SNACKBAR';
const SUCCESS_SNACKBAR = 'snackbar/SUCCESS_SNACKBAR';

export default {
  OPEN_SNACKBAR,
  CLOSE_SNACKBAR,
  ERROR_SNACKBAR,
  INFO_SNACKBAR,
  SUCCESS_SNACKBAR,
};
